# Generated by Django 2.0.5 on 2020-05-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2048, verbose_name='Текст')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Добавлена')),
            ],
        ),
        migrations.CreateModel(
            name='ForumsRazdel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Название')),
                ('quantity_themes', models.SmallIntegerField(default=0, verbose_name='Количество тем')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Добавлена')),
            ],
            options={
                'verbose_name': 'Раздел форума',
                'verbose_name_plural': 'Разделы Форума',
                'ordering': ['date_create'],
            },
        ),
        migrations.CreateModel(
            name='ForumsTema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Название')),
                ('text', models.TextField(max_length=2048, verbose_name='Текст')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Добавлена')),
                ('photo', models.ImageField(blank=True, upload_to='gamePhoto', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['name'],
            },
        ),
    ]
