# Generated by Django 2.0.5 on 2020-05-09 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forums', '0001_initial'),
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forumstema',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='forumstema',
            name='razdel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.ForumsRazdel', to_field='name', verbose_name='Раздел'),
        ),
        migrations.AddField(
            model_name='forumsrazdel',
            name='name_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Game', to_field='name', verbose_name='Игра'),
        ),
        migrations.AddField(
            model_name='forumscomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='forumscomment',
            name='forums',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.ForumsTema', to_field='name', verbose_name='Название темы'),
        ),
    ]
